import { Post, Category, UserProfile } from "./types";

// ─── CATEGORIES ──────────────────────────────────────────────────────────────
export const CATEGORIES: Category[] = [
  { id: "1", name: "AI Prompts", slug: "ai-prompts", icon: "🤖", description: "Curated AI prompts for all models", postCount: 1240, color: "#ff3131" },
  { id: "2", name: "Room Ideas", slug: "room-ideas", icon: "🏠", description: "Stunning room setups and interior inspiration", postCount: 890, color: "#8b5cf6" },
  { id: "3", name: "Setups", slug: "setups", icon: "💻", description: "Desk and productivity setups", postCount: 654, color: "#0ea5e9" },
  { id: "4", name: "Wallpapers", slug: "wallpapers", icon: "🖼️", description: "AI-generated wallpapers", postCount: 2100, color: "#10b981" },
  { id: "5", name: "Quotes", slug: "quotes", icon: "💬", description: "Motivational and aesthetic quotes", postCount: 445, color: "#f59e0b" },
  { id: "6", name: "Fashion", slug: "fashion", icon: "👗", description: "AI fashion and style inspiration", postCount: 320, color: "#ec4899" },
  { id: "7", name: "UI Design", slug: "ui-design", icon: "🎨", description: "UI/UX inspiration and prompts", postCount: 780, color: "#6366f1" },
  { id: "8", name: "Productivity", slug: "productivity", icon: "⚡", description: "Productivity tips and setups", postCount: 512, color: "#14b8a6" },
  { id: "9", name: "Gaming", slug: "gaming", icon: "🎮", description: "Gaming setups and wallpapers", postCount: 1050, color: "#f97316" },
  { id: "10", name: "Cinematic", slug: "cinematic", icon: "🎬", description: "Cinematic and film-inspired AI art", postCount: 876, color: "#a855f7" },
  { id: "11", name: "Interiors", slug: "interiors", icon: "🛋️", description: "Luxury interior design inspiration", postCount: 430, color: "#84cc16" },
  { id: "12", name: "3D Art", slug: "3d-art", icon: "💎", description: "3D renders and AI sculptures", postCount: 560, color: "#06b6d4" },
];

// ─── TRENDING TAGS ────────────────────────────────────────────────────────────
export const TRENDING_TAGS = [
  "#MidjourneyPrompts",
  "#UIDesign",
  "#CinematicAI",
  "#RoomSetup",
  "#DarkAesthetic",
  "#ProductivitySetup",
  "#AIArt",
  "#GamingSetup",
  "#Wallpapers",
  "#InteriorDesign",
];

// ─── MOCK USERS ───────────────────────────────────────────────────────────────
export const MOCK_USERS: UserProfile[] = [
  {
    uid: "u1",
    email: "alex@example.com",
    displayName: "Alex Designs",
    username: "alex_designs",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=alex",
    bio: "Creative director crafting AI inspirations daily. 5+ years in digital design.",
    website: "https://alexdesigns.co",
    isCreator: true,
    isAdmin: false,
    followerCount: 12500,
    followingCount: 342,
    savedCount: 890,
    postCount: 145,
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2024-09-14T00:00:00Z",
    stats: { viewsThisMonth: 45000, savesThisMonth: 1200, followersGain: 340 },
  },
  {
    uid: "u2",
    email: "maya@example.com",
    displayName: "Maya Chen",
    username: "maya_creates",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=maya",
    bio: "AI artist & prompt engineer. Making the impossible, possible.",
    isCreator: true,
    isAdmin: false,
    followerCount: 8900,
    followingCount: 211,
    savedCount: 654,
    postCount: 98,
    createdAt: "2024-02-20T00:00:00Z",
    updatedAt: "2024-09-12T00:00:00Z",
    stats: { viewsThisMonth: 28000, savesThisMonth: 780, followersGain: 210 },
  },
  {
    uid: "u3",
    email: "jake@example.com",
    displayName: "Jake Winters",
    username: "jake_winters",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=jake",
    bio: "Midjourney specialist. Turning words into worlds.",
    isCreator: true,
    isAdmin: false,
    followerCount: 22000,
    followingCount: 89,
    savedCount: 2100,
    postCount: 267,
    createdAt: "2023-11-05T00:00:00Z",
    updatedAt: "2024-09-13T00:00:00Z",
    stats: { viewsThisMonth: 72000, savesThisMonth: 3400, followersGain: 580 },
  },
  {
    uid: "u4",
    email: "sofia@example.com",
    displayName: "Sofia Laurent",
    username: "sofia_art",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=sofia",
    bio: "Interior AI artist. Dream spaces made real.",
    isCreator: true,
    isAdmin: false,
    followerCount: 6700,
    followingCount: 178,
    savedCount: 430,
    postCount: 56,
    createdAt: "2024-03-10T00:00:00Z",
    updatedAt: "2024-09-10T00:00:00Z",
    stats: { viewsThisMonth: 19000, savesThisMonth: 560, followersGain: 145 },
  },
  {
    uid: "u5",
    email: "ryan@example.com",
    displayName: "Ryan Park",
    username: "ryan_prompts",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=ryan",
    bio: "Prompt engineer & workflow optimizer. Helping creators do more.",
    isCreator: true,
    isAdmin: false,
    followerCount: 15300,
    followingCount: 423,
    savedCount: 1560,
    postCount: 189,
    createdAt: "2023-12-01T00:00:00Z",
    updatedAt: "2024-09-11T00:00:00Z",
    stats: { viewsThisMonth: 54000, savesThisMonth: 2100, followersGain: 430 },
  },
];

// ─── MOCK POSTS ───────────────────────────────────────────────────────────────
const createPost = (
  id: string,
  overrides: Partial<Post>
): Post => ({
  id,
  slug: overrides.slug || `post-${id}`,
  title: "Cinematic AI Workspace",
  seoTitle: "Cinematic AI Workspace | PromptNest AI",
  seoDescription: "Discover stunning cinematic AI workspace prompts and inspiration.",
  description: "An immersive workspace setup inspired by cinematic aesthetics. Perfect for creators who want a dark, moody environment that sparks creativity.",
  featuredImage: {
    url: `https://picsum.photos/seed/${id}/800/600`,
    alt: "Featured image",
    width: 800,
    height: 600,
  },
  images: [
    { url: `https://picsum.photos/seed/${id}a/1200/900`, alt: "Gallery 1", width: 1200, height: 900, thumb: `https://picsum.photos/seed/${id}a/400/300` },
    { url: `https://picsum.photos/seed/${id}b/1200/900`, alt: "Gallery 2", width: 1200, height: 900, thumb: `https://picsum.photos/seed/${id}b/400/300` },
    { url: `https://picsum.photos/seed/${id}c/1200/900`, alt: "Gallery 3", width: 1200, height: 900, thumb: `https://picsum.photos/seed/${id}c/400/300` },
  ],
  prompt: {
    title: "Cinematic Dark Workspace",
    text: "A stunning cinematic workspace, ultra-realistic 8K, dark moody atmosphere, dramatic rim lighting, professional photography, neon RGB accents, multiple monitors, mechanical keyboard, minimal cluttered desk, bokeh background, shot with Sony A7R IV, 35mm lens, f/2.8 --ar 16:9 --style raw --v 6.1",
    model: "Midjourney",
    difficulty: "Intermediate",
    cost: 0,
  },
  tags: ["AI", "Workspace", "Cinematic", "Dark Aesthetic", "Setup"],
  category: CATEGORIES[0],
  author: MOCK_USERS[0],
  stats: {
    views: 12500,
    likes: 2400,
    saves: 890,
    shares: 340,
    comments: 34,
  },
  isFeatured: false,
  isTrending: false,
  status: "published",
  publishedAt: "2024-09-14T00:00:00Z",
  createdAt: "2024-09-14T00:00:00Z",
  updatedAt: "2024-09-14T00:00:00Z",
  ...overrides,
});

export const MOCK_POSTS: Post[] = [
  createPost("1", {
    slug: "cinematic-ai-workspace",
    title: "Cinematic AI Workspace Setup",
    featuredImage: { url: "https://picsum.photos/seed/1001/800/600", alt: "Cinematic workspace", width: 800, height: 600 },
    category: CATEGORIES[2],
    tags: ["Workspace", "Setup", "Cinematic", "Dark"],
    stats: { views: 12500, likes: 2400, saves: 890, shares: 340, comments: 34 },
    isFeatured: true,
    isTrending: true,
    author: MOCK_USERS[0],
  }),
  createPost("2", {
    slug: "neon-gaming-room",
    title: "Neon Gaming Room Dream Setup",
    featuredImage: { url: "https://picsum.photos/seed/1002/800/900", alt: "Gaming room", width: 800, height: 900 },
    category: CATEGORIES[8],
    tags: ["Gaming", "Neon", "Room", "RGB"],
    stats: { views: 8900, likes: 1800, saves: 654, shares: 210, comments: 28 },
    isTrending: true,
    author: MOCK_USERS[2],
  }),
  createPost("3", {
    slug: "midjourney-fantasy-landscape",
    title: "Midjourney Fantasy Landscape Prompt",
    featuredImage: { url: "https://picsum.photos/seed/1003/800/700", alt: "Fantasy landscape", width: 800, height: 700 },
    category: CATEGORIES[0],
    tags: ["Midjourney", "Fantasy", "Landscape", "Prompt"],
    stats: { views: 22000, likes: 4100, saves: 2100, shares: 780, comments: 67 },
    isTrending: true,
    author: MOCK_USERS[2],
  }),
  createPost("4", {
    slug: "minimal-luxury-bedroom",
    title: "Minimal Luxury Bedroom Interior",
    featuredImage: { url: "https://picsum.photos/seed/1004/800/650", alt: "Luxury bedroom", width: 800, height: 650 },
    category: CATEGORIES[10],
    tags: ["Interior", "Luxury", "Minimal", "Bedroom"],
    stats: { views: 6700, likes: 1340, saves: 430, shares: 123, comments: 19 },
    author: MOCK_USERS[3],
  }),
  createPost("5", {
    slug: "dark-aesthetic-wallpaper-pack",
    title: "Dark Aesthetic Wallpaper Pack",
    featuredImage: { url: "https://picsum.photos/seed/1005/800/600", alt: "Dark wallpaper", width: 800, height: 600 },
    category: CATEGORIES[3],
    tags: ["Wallpaper", "Dark", "Aesthetic", "AI Art"],
    stats: { views: 15300, likes: 2900, saves: 1560, shares: 445, comments: 42 },
    isTrending: true,
    author: MOCK_USERS[4],
  }),
  createPost("6", {
    slug: "ui-design-prompt-collection",
    title: "UI Design Prompt Collection 2024",
    featuredImage: { url: "https://picsum.photos/seed/1006/800/800", alt: "UI design prompts", width: 800, height: 800 },
    category: CATEGORIES[6],
    tags: ["UI Design", "Prompts", "ChatGPT", "Design System"],
    stats: { views: 9800, likes: 1900, saves: 780, shares: 290, comments: 31 },
    author: MOCK_USERS[0],
  }),
  createPost("7", {
    slug: "cinematic-portrait-midjourney",
    title: "Cinematic Portrait Photography Prompts",
    featuredImage: { url: "https://picsum.photos/seed/1007/800/950", alt: "Cinematic portrait", width: 800, height: 950 },
    category: CATEGORIES[9],
    tags: ["Portrait", "Cinematic", "Photography", "Midjourney"],
    stats: { views: 18700, likes: 3500, saves: 1200, shares: 560, comments: 55 },
    isFeatured: true,
    author: MOCK_USERS[1],
  }),
  createPost("8", {
    slug: "productivity-desk-setup",
    title: "Ultimate Productivity Desk Setup",
    featuredImage: { url: "https://picsum.photos/seed/1008/800/680", alt: "Productivity setup", width: 800, height: 680 },
    category: CATEGORIES[7],
    tags: ["Productivity", "Desk", "Setup", "Minimal"],
    stats: { views: 11200, likes: 2100, saves: 920, shares: 320, comments: 38 },
    author: MOCK_USERS[4],
  }),
  createPost("9", {
    slug: "ai-fashion-editorial",
    title: "AI Fashion Editorial Prompts",
    featuredImage: { url: "https://picsum.photos/seed/1009/800/1000", alt: "Fashion editorial", width: 800, height: 1000 },
    category: CATEGORIES[5],
    tags: ["Fashion", "Editorial", "AI Art", "Style"],
    stats: { views: 7400, likes: 1450, saves: 520, shares: 178, comments: 24 },
    author: MOCK_USERS[1],
  }),
  createPost("10", {
    slug: "3d-architecture-render",
    title: "3D Architecture Visualization Prompts",
    featuredImage: { url: "https://picsum.photos/seed/1010/800/750", alt: "3D architecture", width: 800, height: 750 },
    category: CATEGORIES[11],
    tags: ["3D", "Architecture", "Visualization", "Render"],
    stats: { views: 14600, likes: 2700, saves: 1100, shares: 410, comments: 46 },
    isTrending: true,
    author: MOCK_USERS[2],
  }),
  createPost("11", {
    slug: "sunset-room-aesthetic",
    title: "Sunset Aesthetic Room Ideas",
    featuredImage: { url: "https://picsum.photos/seed/1011/800/720", alt: "Sunset room", width: 800, height: 720 },
    category: CATEGORIES[1],
    tags: ["Room", "Sunset", "Aesthetic", "Interior"],
    stats: { views: 5800, likes: 1100, saves: 380, shares: 99, comments: 16 },
    author: MOCK_USERS[3],
  }),
  createPost("12", {
    slug: "motivational-quotes-ai",
    title: "Aesthetic Motivational Quote Cards",
    featuredImage: { url: "https://picsum.photos/seed/1012/800/800", alt: "Quote cards", width: 800, height: 800 },
    category: CATEGORIES[4],
    tags: ["Quotes", "Motivation", "Aesthetic", "Cards"],
    stats: { views: 4200, likes: 890, saves: 320, shares: 145, comments: 12 },
    author: MOCK_USERS[1],
  }),
  createPost("13", {
    slug: "neon-city-prompts",
    title: "Neon Cyberpunk City Prompts",
    featuredImage: { url: "https://picsum.photos/seed/1013/800/600", alt: "Neon city", width: 800, height: 600 },
    category: CATEGORIES[0],
    tags: ["Cyberpunk", "Neon", "City", "AI Prompts"],
    stats: { views: 25000, likes: 4800, saves: 2400, shares: 890, comments: 78 },
    isFeatured: true,
    isTrending: true,
    author: MOCK_USERS[2],
  }),
  createPost("14", {
    slug: "modern-living-room-ideas",
    title: "Modern Minimalist Living Room Ideas",
    featuredImage: { url: "https://picsum.photos/seed/1014/800/640", alt: "Living room", width: 800, height: 640 },
    category: CATEGORIES[10],
    tags: ["Living Room", "Modern", "Minimal", "Interior"],
    stats: { views: 8100, likes: 1560, saves: 620, shares: 205, comments: 27 },
    author: MOCK_USERS[3],
  }),
  createPost("15", {
    slug: "stable-diffusion-masterpack",
    title: "Stable Diffusion Master Prompt Pack",
    featuredImage: { url: "https://picsum.photos/seed/1015/800/700", alt: "Stable diffusion", width: 800, height: 700 },
    category: CATEGORIES[0],
    tags: ["Stable Diffusion", "Prompts", "AI Art", "Master Pack"],
    stats: { views: 31000, likes: 5600, saves: 3100, shares: 1200, comments: 94 },
    isFeatured: true,
    isTrending: true,
    author: MOCK_USERS[4],
  }),
  createPost("16", {
    slug: "rgb-gaming-desktop-setup",
    title: "Ultimate RGB Gaming Desktop Setup",
    featuredImage: { url: "https://picsum.photos/seed/1016/800/560", alt: "RGB gaming setup", width: 800, height: 560 },
    category: CATEGORIES[8],
    tags: ["Gaming", "RGB", "Desktop", "Setup"],
    stats: { views: 13400, likes: 2500, saves: 1040, shares: 380, comments: 44 },
    author: MOCK_USERS[2],
  }),
  createPost("17", {
    slug: "ai-logo-design-prompts",
    title: "AI Logo Design Prompts for Creators",
    featuredImage: { url: "https://picsum.photos/seed/1017/800/800", alt: "Logo design prompts", width: 800, height: 800 },
    category: CATEGORIES[6],
    tags: ["Logo", "Design", "Branding", "AI Prompts"],
    stats: { views: 10700, likes: 2050, saves: 860, shares: 310, comments: 35 },
    author: MOCK_USERS[0],
  }),
  createPost("18", {
    slug: "dark-forest-fantasy-art",
    title: "Dark Forest Fantasy AI Art Prompts",
    featuredImage: { url: "https://picsum.photos/seed/1018/800/900", alt: "Dark forest fantasy", width: 800, height: 900 },
    category: CATEGORIES[9],
    tags: ["Fantasy", "Dark", "Forest", "AI Art"],
    stats: { views: 16800, likes: 3200, saves: 1340, shares: 490, comments: 52 },
    isTrending: true,
    author: MOCK_USERS[1],
  }),
  createPost("19", {
    slug: "cozy-workspace-aesthetic",
    title: "Cozy Workspace Aesthetic Setup Ideas",
    featuredImage: { url: "https://picsum.photos/seed/1019/800/680", alt: "Cozy workspace", width: 800, height: 680 },
    category: CATEGORIES[2],
    tags: ["Cozy", "Workspace", "Aesthetic", "Warm"],
    stats: { views: 9300, likes: 1780, saves: 740, shares: 260, comments: 30 },
    author: MOCK_USERS[4],
  }),
  createPost("20", {
    slug: "luxury-penthouse-interior",
    title: "Luxury Penthouse Interior Design AI",
    featuredImage: { url: "https://picsum.photos/seed/1020/800/760", alt: "Penthouse interior", width: 800, height: 760 },
    category: CATEGORIES[10],
    tags: ["Luxury", "Penthouse", "Interior", "Modern"],
    stats: { views: 20500, likes: 3900, saves: 1680, shares: 620, comments: 61 },
    isFeatured: true,
    author: MOCK_USERS[3],
  }),
];

export const FEATURED_POST = MOCK_POSTS[0];

export const TRENDING_POSTS = MOCK_POSTS.filter((p) => p.isTrending);

export const FEATURED_POSTS = MOCK_POSTS.filter((p) => p.isFeatured);

// Admin email is stored in .env.local as ADMIN_EMAIL (server-side only, never exposed to client)
// Usage: process.env.ADMIN_EMAIL  ← only in Server Components / API routes / middleware
export const ADMIN_EMAIL = process.env.ADMIN_EMAIL ?? "";

export const SITE_CONFIG = {
  name: "PromptNest AI",
  description: "Discover, share, and monetize AI prompts and inspirations. Curated prompts, stunning visuals, and endless creativity.",
  url: "https://promptnest.ai",
  ogImage: "/og-image.png",
  twitterHandle: "@promptnestai",
};
